name: ffxiv
description: "ItemDatabase 3rd party for Final Fantasy 14. support for korean server data only now."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.3.1
  firebase_storage: ^12.2.0
  firebase_pagination: ^4.0.1
  firebase_data_connect: ^0.1.2+1
  flutter_search_bar: ^3.0.0
  cloud_firestore: ^5.0.2
  crypto: ^3.0.3
  provider: ^6.0.0
  html_parser_plus: ^0.1.4
  url_launcher: ^6.0.0
  flutter_color: ^2.1.0
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+17
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.2.7
  flutter_plugin_android_lifecycle: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
