// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpX9N9lkJk2FVz31pTZUyIVo92mRoNNps',
    appId: '1:961203961599:web:a5f09d549da183ec1516ca',
    messagingSenderId: '961203961599',
    projectId: 'ffxiv-database-a42b0',
    authDomain: 'ffxiv-database-a42b0.firebaseapp.com',
    databaseURL: 'https://ffxiv-database-a42b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffxiv-database-a42b0.appspot.com',
    measurementId: 'G-0SV4QFCHT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTD0IV3E9ps4dbFyyPqXkcm079CbN0dI',
    appId: '1:961203961599:android:480b0df5b92f6e8b1516ca',
    messagingSenderId: '961203961599',
    projectId: 'ffxiv-database-a42b0',
    databaseURL: 'https://ffxiv-database-a42b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffxiv-database-a42b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmXz2radm8gjLM7uyVtmWkfV9hzxDuwaE',
    appId: '1:961203961599:ios:8ad6d3d21d37cb601516ca',
    messagingSenderId: '961203961599',
    projectId: 'ffxiv-database-a42b0',
    databaseURL: 'https://ffxiv-database-a42b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffxiv-database-a42b0.appspot.com',
    iosBundleId: 'com.letelumiere.ffxiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmXz2radm8gjLM7uyVtmWkfV9hzxDuwaE',
    appId: '1:961203961599:ios:8ad6d3d21d37cb601516ca',
    messagingSenderId: '961203961599',
    projectId: 'ffxiv-database-a42b0',
    databaseURL: 'https://ffxiv-database-a42b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffxiv-database-a42b0.appspot.com',
    iosBundleId: 'com.letelumiere.ffxiv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpX9N9lkJk2FVz31pTZUyIVo92mRoNNps',
    appId: '1:961203961599:web:a4198b36bbaae8851516ca',
    messagingSenderId: '961203961599',
    projectId: 'ffxiv-database-a42b0',
    authDomain: 'ffxiv-database-a42b0.firebaseapp.com',
    databaseURL: 'https://ffxiv-database-a42b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ffxiv-database-a42b0.appspot.com',
    measurementId: 'G-GEH3K5R2N1',
  );
}
